name: first

on: push

jobs:
    jobs1:
        name: first job
        runs-on: ubuntu-latest
        steps:
        - name: step 1
          uses: actions/checkout@v2
          with:
            repository: firdausng/TestManagementApp
            ref: master
            path: ./TestManagementApp
        - name: step 2
          run: |
               ld -ltr
    jobs:
        name: second job
        runs-on: windows-latest
        steps:
        - name: step 1
          uses: actions/checkout@v2
        - name: step 2
          run: "Get-ChildItem Env: | Sort-Object Name"
